# Generated by Django 2.1.3 on 2019-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='leaps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_leaps',
            field=models.FloatField(null=True),
        ),
    ]
